# frozen_string_literal: true

require "json"
require "time"

module DeuteriumSite
  module PostIndex
    class IndexError < StandardError; end

    JSON_NAME = "index.json"
    JSONL_NAME = "index.jsonl"
    ORIGIN = %r{\Ahttps?://[^/]+\z}.freeze
    # A fenced code block opener at the start of a line (CommonMark allows up
    # to three leading spaces). This is the same code the site renders inside
    # framed code blocks, so it is the meaningful "contains code" signal.
    FENCED_CODE = /\A {0,3}(?:`{3,}|~{3,})/.freeze

    module_function

    # The origin that will serve the generated site. Failing loudly on a bad
    # `url` is better than emitting routes that do not resolve.
    def origin(site)
      value = site.config.fetch("url", "").to_s.sub(%r{/+\z}, "")
      raise IndexError, "site.url must be an HTTP(S) origin" unless value.match?(ORIGIN)

      value
    end

    def route(site, post)
      "#{origin(site)}#{site.baseurl.to_s}#{post.url}"
    end

    def iso8601(date)
      return date.xmlschema if date.respond_to?(:xmlschema)

      Time.parse(date.to_s).xmlschema
    end

    def has_code?(post)
      post.content.to_s.each_line.any? { |line| line.match?(FENCED_CODE) }
    end

    # One bodyless entry per published post. The tags array mirrors the
    # canonical post data after tag aliasing, exactly as the site renders it.
    def entry(site, post)
      {
        "title"       => post.data["title"].to_s,
        "date"        => iso8601(post.date),
        "route"       => route(site, post),
        "section"     => post.data["section"].to_s,
        "tags"        => Array(post.data["tags"]).map(&:to_s),
        "description" => post.data["description"].to_s,
        "has_math"    => post.data["mathjax"] == true,
        "has_code"    => has_code?(post),
      }
    end

    # Newest post first; ties broken by route so the output is a stable total
    # order regardless of filesystem enumeration order.
    def entries(site)
      site.posts.docs.sort do |left, right|
        comparison = right.date <=> left.date
        comparison.zero? ? (left.url <=> right.url) : comparison
      end.map { |post| entry(site, post) }
    end

    def json_bytes(entries)
      "#{JSON.pretty_generate(entries)}\n"
    end

    def jsonl_bytes(entries)
      entries.map { |entry| "#{JSON.generate(entry)}\n" }.join
    end
  end

  # A generated byte string has no source file to stat or copy, so both the
  # content and the write are fully owned here.
  class IndexArtifact < Jekyll::StaticFile
    def initialize(site, name, bytes)
      super(site, site.source, "", name)
      @bytes = bytes
    end

    def write(dest)
      dest_path = destination(dest)
      FileUtils.mkdir_p(File.dirname(dest_path))
      File.binwrite(dest_path, @bytes)
      true
    end
  end

  class DeuteriumPostIndex < Jekyll::Generator
    safe true
    priority :low

    def generate(site)
      entries = PostIndex.entries(site)
      site.static_files << IndexArtifact.new(site, PostIndex::JSON_NAME, PostIndex.json_bytes(entries))
      site.static_files << IndexArtifact.new(site, PostIndex::JSONL_NAME, PostIndex.jsonl_bytes(entries))
    end
  end
end
